name: pytorch-CycleGAN-and-pix2pix
channels:
- pytorch
- defaults
dependencies:
- python=3.6
- pytorch=1.4.0
- scipy
- pip:
  - dominate==2.4.0
  - torchvision==0.5.0
  - Pillow==6.1.0
  - numpy==1.16.4
  - visdom==0.1.8
