name: pytorch-CycleGAN-and-pix2pix
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.14=py38h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - fftw=3.3.9=h27cfd23_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuv=1.40.0=h7b6447c_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.2.2=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
  - readline=8.1.2=h7f8727e_1
  - scipy=1.9.1=py38h14f4228_0
  - setuptools=63.4.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.3.0=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - charset-normalizer==2.1.1
    - click==8.1.3
    - docker-pycreds==0.4.0
    - dominate==2.6.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - idna==3.4
    - imageio==2.22.1
    - networkx==2.8.7
    - numpy==1.19.2
    - packaging==21.3
    - pathtools==0.1.2
    - pillow==9.2.0
    - promise==2.3
    - protobuf==3.20.3
    - psutil==5.9.2
    - pyparsing==3.0.9
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - requests==2.28.1
    - scikit-image==0.19.3
    - sentry-sdk==1.9.10
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - smmap==5.0.0
    - tifffile==2022.8.12
    - torchfile==0.1.0
    - torchvision==0.9.1
    - tornado==6.2
    - urllib3==1.26.12
    - visdom==0.1.8
    - wandb==0.12.18
    - websocket-client==1.4.1
prefix: /n/home09/scajasordonez/anaconda3/envs/pytorch-CycleGAN-and-pix2pix
